"""Building and rendering a PR description.

`build_report` assembles a plain-dict report (the JSON output format) from
parsed commits, diff stats, and journal evidence; `render_markdown` turns
that report into the Markdown PR body. Splitting the two keeps rendering a
pure function of the report, and makes the JSON format the single source
of truth for what a report contains.

Every sentence in the output is traceable to an input record. When a
section has no data, it says so explicitly ("no session journal provided")
rather than inventing anything — absence of evidence is itself information
for a reviewer.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence

from .conventional import Commit
from .evidence import Check
from .filestats import DiffSummary
from .grouping import SECTION_TITLES, group_commits
from .journal import Journal

__all__ = ["suggest_title", "build_report", "render_markdown"]

_SUMMARY_TYPES = ("feat", "fix", "perf", "refactor", "revert")
_MARKER = "<!-- generated by mergescribe v{version} -->"


def _capitalize(text: str) -> str:
    return text[:1].upper() + text[1:] if text else text


def suggest_title(commits: Sequence[Commit]) -> str:
    """Deterministic PR title suggestion.

    * one commit → its subject verbatim;
    * otherwise → the first feature (falling back to first fix, then first
      commit), re-rendered as a conventional header, with the remaining
      commit count appended so the title never overclaims.
    """
    if not commits:
        return ""
    if len(commits) == 1:
        return commits[0].subject
    primary = next(
        (commit for commit in commits if commit.type == "feat"),
        next((commit for commit in commits if commit.type == "fix"), commits[0]),
    )
    rest = len(commits) - 1
    if primary.conventional:
        scope = f"({primary.scope})" if primary.scope else ""
        bang = "!" if primary.breaking else ""
        head = f"{primary.type}{scope}{bang}: {primary.description}"
    else:
        head = primary.subject
    return f"{head} (+{rest} more commit{'s' if rest != 1 else ''})"


def _commit_entry(commit: Commit) -> Dict[str, object]:
    return {
        "sha": commit.short_sha,
        "type": commit.type,
        "scope": commit.scope,
        "breaking": commit.breaking,
        "description": commit.description,
        "issues": list(commit.issues),
        "closes": list(commit.closes),
    }


def build_report(
    commits: Sequence[Commit],
    diff: Optional[DiffSummary] = None,
    checks: Optional[Sequence[Check]] = None,
    journal: Optional[Journal] = None,
    base: str = "",
    head: str = "",
) -> Dict[str, object]:
    """Assemble the report dict that both the JSON and Markdown outputs use."""
    sections = [
        {
            "type": key,
            "title": SECTION_TITLES[key],
            "commits": [_commit_entry(commit) for commit in entries],
        }
        for key, entries in group_commits(commits)
    ]

    breaking = []
    for commit in commits:
        if commit.breaking:
            notes = list(commit.breaking_notes) or [commit.description]
            breaking.append(
                {"sha": commit.short_sha, "scope": commit.scope, "notes": notes}
            )

    closes: List[int] = []
    refs: List[int] = []
    for commit in commits:
        for number in commit.closes:
            if number not in closes:
                closes.append(number)
    for commit in commits:
        for number in commit.issues:
            if number not in closes and number not in refs:
                refs.append(number)

    report: Dict[str, object] = {
        "tool": "mergescribe",
        "base": base,
        "head": head,
        "title": suggest_title(commits),
        "commit_count": len(commits),
        "sections": sections,
        "breaking": breaking,
        "closes": closes,
        "references": refs,
    }

    if diff is not None:
        report["diff"] = {
            "files": diff.files,
            "added": diff.added,
            "deleted": diff.deleted,
            "binary": diff.binary,
            "by_area": [
                {"area": area, "files": files, "added": added, "deleted": deleted}
                for area, (files, added, deleted) in diff.by_area
            ],
            "top": [
                {"path": change.path, "added": change.added, "deleted": change.deleted}
                for change in diff.top
            ],
        }

    if journal is not None:
        report["journal"] = {
            "sources": list(journal.sources),
            "events": len(journal.events),
            "skipped": journal.skipped,
            "checks": [
                {
                    "category": check.category,
                    "command": check.command,
                    "runs": check.runs,
                    "exit_code": check.exit_code,
                    "outcome": check.outcome,
                }
                for check in (checks or [])
            ],
            "notes": [
                {"kind": event.kind, "text": event.text} for event in journal.notes()
            ],
        }

    return report


def render_markdown(report: Dict[str, object], version: str, max_summary: int = 8) -> str:
    """Render a report dict to the Markdown PR body."""
    lines: List[str] = []

    # Reconstruct commit objects lightly from the report sections for summary.
    sections = report.get("sections", [])
    lines.append("## Summary")
    lines.append("")
    summary_entries: List[Dict[str, object]] = []
    for section in sections:  # type: ignore[union-attr]
        if section["type"] in _SUMMARY_TYPES:
            summary_entries.extend(section["commits"])  # type: ignore[index]
    if not summary_entries:
        for section in sections:  # type: ignore[union-attr]
            summary_entries.extend(section["commits"])  # type: ignore[index]
    for entry in summary_entries[:max_summary]:
        text = _capitalize(str(entry["description"]))
        if entry.get("breaking"):
            text = f"**Breaking:** {text}"
        lines.append(f"- {text}")
    hidden = len(summary_entries) - max_summary
    if hidden > 0:
        lines.append(f"- …and {hidden} more (see Changes below)")

    lines.append("")
    lines.append("## Changes")
    lines.append("")
    for section in sections:  # type: ignore[union-attr]
        lines.append(f"### {section['title']}")
        lines.append("")
        for entry in section["commits"]:  # type: ignore[index]
            scope = f"**{entry['scope']}:** " if entry["scope"] else ""
            bang = " ⚠" if entry.get("breaking") else ""
            lines.append(
                f"- {scope}{entry['description']}{bang} (`{entry['sha']}`)"
            )
        lines.append("")

    breaking = report.get("breaking", [])
    if breaking:
        lines.append("## Breaking changes")
        lines.append("")
        for item in breaking:  # type: ignore[union-attr]
            scope = f"**{item['scope']}:** " if item["scope"] else ""
            for note in item["notes"]:  # type: ignore[index]
                lines.append(f"- {scope}{note} (`{item['sha']}`)")
        lines.append("")

    lines.append("## Verification")
    lines.append("")
    journal = report.get("journal")
    if journal is None:
        lines.append("_No session journal provided — verification not recorded._")
    else:
        checks = journal["checks"]  # type: ignore[index]
        if not checks:
            lines.append("_Journal contains no recognized test/lint/build commands._")
        else:
            lines.append("| Check | Command | Runs | Last result |")
            lines.append("|---|---|---|---|")
            for check in checks:
                lines.append(
                    f"| {check['category']} | `{check['command']}` "
                    f"| {check['runs']} | {check['outcome']} |"
                )
    lines.append("")

    if journal is not None and journal["notes"]:  # type: ignore[index]
        lines.append("## Session notes")
        lines.append("")
        for note in journal["notes"]:  # type: ignore[index]
            prefix = "decision: " if note["kind"] == "decision" else ""
            lines.append(f"- {prefix}{note['text']}")
        lines.append("")

    diff = report.get("diff")
    if diff is not None:
        lines.append("## Diff at a glance")
        lines.append("")
        lines.append(
            f"{diff['files']} files changed, +{diff['added']} −{diff['deleted']}"  # type: ignore[index]
        )
        lines.append("")
        lines.append("| Area | Files | + | − |")
        lines.append("|---|---|---|---|")
        for area in diff["by_area"]:  # type: ignore[index]
            lines.append(
                f"| {area['area']} | {area['files']} | {area['added']} | {area['deleted']} |"
            )
        lines.append("")

    closes = report.get("closes", [])
    refs = report.get("references", [])
    if closes or refs:
        lines.append("## Linked issues")
        lines.append("")
        if closes:
            lines.append("Closes " + ", ".join(f"#{number}" for number in closes) + ".")  # type: ignore[union-attr]
        if refs:
            lines.append("Refs " + ", ".join(f"#{number}" for number in refs) + ".")  # type: ignore[union-attr]
        lines.append("")

    lines.append("---")
    lines.append("")
    journal_note = ""
    if journal is not None:
        count = len(journal["sources"])  # type: ignore[index]
        journal_note = f" and {count} session journal{'s' if count != 1 else ''}"
    commit_count = int(report["commit_count"])  # type: ignore[arg-type]
    lines.append(
        f"_Generated deterministically by mergescribe from "
        f"{commit_count} commit{'s' if commit_count != 1 else ''}{journal_note} — no LLM involved._"
    )
    lines.append(_MARKER.format(version=version))
    lines.append("")
    return "\n".join(lines)
