"""PR report assembly and Markdown rendering."""

from mergescribe.conventional import parse_commit
from mergescribe.evidence import collect_checks
from mergescribe.filestats import summarize
from mergescribe.gitlog import FileChange
from mergescribe.journal import Journal, JournalEvent
from mergescribe.prbody import build_report, render_markdown, suggest_title


def make(subject, body="", sha="a"):
    return parse_commit(sha * 40, "Dev", "2026-07-10T09:00:00+00:00", subject, body)


def journal_with(events):
    return Journal(events=tuple(events), sources=("session.jsonl",))


class TestSuggestTitle:
    def test_single_commit_uses_subject_verbatim(self):
        assert suggest_title([make("feat(api): add pagination")]) == "feat(api): add pagination"
        assert suggest_title([]) == ""

    def test_multi_commit_prefers_first_feature(self):
        title = suggest_title([make("fix: a"), make("feat(api): add pagination"), make("docs: c")])
        assert title == "feat(api): add pagination (+2 more commits)"

    def test_falls_back_to_first_fix_then_first_commit(self):
        assert suggest_title([make("docs: d"), make("fix: crash")]).startswith("fix: crash")
        assert suggest_title([make("docs: d"), make("chore: c")]).startswith("docs: d")
        # A breaking bang must survive the round trip into the title.
        title = suggest_title([make("feat(api)!: drop v1"), make("docs: d")])
        assert title.startswith("feat(api)!: drop v1")


class TestBuildReport:
    def test_report_shape(self):
        report = build_report([make("feat: x")], base="main", head="HEAD")
        assert report["tool"] == "mergescribe"
        assert report["commit_count"] == 1
        assert report["sections"][0]["title"] == "Features"

    def test_closes_deduplicated_and_references_disjoint(self):
        commits = [make("fix: a mentions #9", "Fixes #7"), make("fix: b", "Closes: #7")]
        report = build_report(commits)
        assert report["closes"] == [7]
        assert report["references"] == [9]

    def test_breaking_uses_footer_note_over_description(self):
        commit = make("refactor!: config rework", "BREAKING CHANGE: keys are nested now")
        report = build_report([commit])
        assert report["breaking"][0]["notes"] == ["keys are nested now"]

    def test_journal_section_includes_checks_and_notes(self):
        events = [
            JournalEvent(kind="command", text="pytest -q", exit_code=0),
            JournalEvent(kind="decision", text="kept v1 wire format"),
        ]
        report = build_report(
            [make("feat: x")], checks=collect_checks(events), journal=journal_with(events)
        )
        assert report["journal"]["checks"][0]["outcome"] == "pass (exit 0)"
        assert report["journal"]["notes"][0]["kind"] == "decision"


class TestRenderMarkdown:
    def render(self, commits, **kwargs):
        report = build_report(commits, **kwargs)
        return render_markdown(report, version="0.1.0")

    def test_sections_in_order_with_generator_marker(self):
        body = self.render([make("feat: add pagination"), make("fix: null cursor")])
        assert body.index("## Summary") < body.index("## Changes") < body.index("## Verification")
        assert "<!-- generated by mergescribe v0.1.0 -->" in body

    def test_summary_bullets_capitalized_and_truncated(self):
        body = self.render([make("feat: add pagination")])
        assert "- Add pagination" in body
        commits = [make(f"feat: feature number {index}", sha=chr(ord("a") + index)) for index in range(10)]
        long_body = render_markdown(build_report(commits), version="0.1.0", max_summary=3)
        assert "…and 7 more (see Changes below)" in long_body

    def test_verification_section_table_or_explicit_absence(self):
        # Absence of evidence is information: the reader must not assume tests ran.
        assert "No session journal provided" in self.render([make("feat: x")])
        journal = journal_with([JournalEvent(kind="note", text="hi")])
        with_journal = self.render([make("feat: x")], journal=journal, checks=[])
        assert "no recognized test/lint/build commands" in with_journal
        events = [JournalEvent(kind="command", text="pytest -q", exit_code=0)]
        body = self.render(
            [make("feat: x")], journal=journal_with(events), checks=collect_checks(events)
        )
        assert "| test | `pytest -q` | 1 | pass (exit 0) |" in body

    def test_breaking_section_rendered(self):
        body = self.render([make("feat!: drop v1 endpoints")])
        assert "## Breaking changes" in body
        assert "**Breaking:**" in body

    def test_diff_table_and_linked_issues_rendered(self):
        diff = summarize([FileChange("src/a.py", 10, 2), FileChange("tests/test_a.py", 5, 0)])
        body = self.render(
            [make("fix: a", "Fixes #7"), make("feat: b mentions #9")], diff=diff
        )
        assert "2 files changed, +15 −2" in body
        assert "| source | 1 | 10 | 2 |" in body
        assert "Closes #7." in body
        assert "Refs #9." in body

    def test_footer_pluralizes_commit_count(self):
        # "from 1 commits" would be an embarrassing footer on a one-commit PR.
        assert "from 1 commit —" in self.render([make("feat: x")])
        assert "from 2 commits —" in self.render([make("feat: x"), make("fix: y")])

    def test_rendering_is_deterministic(self):
        commits = [make("feat: x"), make("fix: y", "Fixes #3")]
        assert self.render(commits) == self.render(commits)
